FROM httpd:2.4-alpine

ENV TZ=${TZ:-UTC}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV APP_ROOT=/var/www/app
ENV SERVER_NAME=localhost
ENV DOCUMENT_ROOT=${APP_ROOT}
ENV APACHE_LOG_DIR=${APP_ROOT}/logs
ENV APACHE_RUN_GROUP=www-data
ENV APACHE_RUN_USER=www-data
ENV CERTS_DIR=/etc/ssl/certs-dev

RUN apk add --update --no-cache tzdata

WORKDIR ${APP_ROOT}

RUN mkdir -p ${DOCUMENT_ROOT}
RUN chown -R ${APACHE_RUN_USER}:${APACHE_RUN_USER} ${DOCUMENT_ROOT}

RUN mkdir -p ${CERTS_DIR}
RUN chown -R ${APACHE_RUN_USER}:${APACHE_RUN_USER} ${CERTS_DIR}

RUN ln -s ${APP_ROOT}/index.html ${DOCUMENT_ROOT}

COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./vhosts.conf /usr/local/apache2/conf/extra/vhosts.conf